name: 'Action Image'
description: 'Posts a image on actions (on the given line if provided), useful for CI/CD & End2End screenshots'
branding:
    icon: 'image'
    color: 'black'
inputs:
    GITHUB_TOKEN:
        description: 'Github token, can be secrets.GITHUB_TOKEN'
        required: true
        default: ''
    path:
        description: 'Image path glob (Ex: **/*.png)'
        required: true
        default: ''
    title:
        description: 'Comment title'
        required: false
        default: ''
    uploadHost:
        description: 'Upload host (Default: cloudinary)'
        required: false
        default: 'cloudinary'
    annotationTag:
        description: 'The tag to look for in the provided images base64 name (ex: tests/mytest.spec.js[--]80:40.png)'
        required: false
        default: '[--]'
    annotationLevel:
        description: 'The annotation level (Default: notice | Supported values: notice, warning, failure)'
        required: false
        default: 'notice'
    cloud-name:
        description: 'Cloudinary account name'
        required: false
        default: '<name>'
    api-key:
        description: 'Cloudinary API Key'
        required: false
        default: '<api-key>'
    api-secret:
        description: 'Cloudinary API Secret Key'
        required: false
        default: '<api-secret>'
runs:
    using: 'node16'
    main: './index.mjs'
